Build changes from 77d47089e6cbf972e490c9b7cdf3fa012e8b5342
https://circleci.com/gh/Automattic/vip-go-build/45

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -29,8 +29,46 @@ jobs:
       #   name: Build the thing
       #   command: npm run build-thing
 
+      # @TODO: modify or remove this example
+      - run: echo "Building..."
+      - run:
+          name: Create build directory
+          command: mkdir -p build
+
+      - run:
+          name: Create build readme
+          command: echo "This was built in CI on $(date)" > build/README.md
+
+      # multiple commands can be combined by starting with the |
+      # do not indent with tabs!
+      - run:
+          name: Add some helpful info to the README
+          command: |
+            echo -e "\n\n## Continuous Integration & Continuous Deployment on VIP Go" >> build/README.md
+            echo -e "\nSee our docs in the [VIP Lobby](https://vip.wordpress.com/documentation/automated-build-and-deploy-on-vip-go/)" >> build/README.md
+            echo -e "\n\nThis branch e.g. master-built is created automatically when " >> build/README.md
+            echo "a commit or merge is made to the base branch e.g. master, using [your CircleCI configuration](../.circleci/config.yml), which you can **customize**" >> build/README.md
+
+      # Test to ensure the build was good, do not deploy bad stuff!
+      - run:
+          name: Test the build
+          command: |
+            if [ -f build/README.md ]; then
+              echo "Build succeeded";
+            else
+              echo "Build failed, file missing"; exit 1
+            fi
+
+      # Uncomment this and supply your ssh fingerprint to enable CircleCI to push the built branch to GitHub
+      #- add_ssh_keys:
+      #    fingerprints:
+      #      - "ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff:ff"
+
       # Run the deploy:
       # REQUIRED: If you're amended an existing config, the below are two
       # of the required lines you must add
+      # This will push the result to the {currentbranch}-built branch
       - deploy:
+          name: Deploy -built branch to github
           command: bash <(curl -s "https://raw.githubusercontent.com/Automattic/vip-go-build/master/deploy.sh")
+
